/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Brent
 */
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.GridLayout;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import javax.swing.*;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.util.ArrayList;
import java.util.Arrays;
public class MainFrame extends javax.swing.JFrame {
    
    private final JFileChooser jchooser;
    private final FiniteAutomata fa = new FiniteAutomata();
    private final ArrayList<Character> alphabet = new ArrayList<>();
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        jchooser = new JFileChooser();
        jchooser.setFileFilter(new FileNameExtensionFilter("TXT documents", "txt"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblStartState = new javax.swing.JLabel();
        lblAcceptStates = new javax.swing.JLabel();
        lblAlphabet = new javax.swing.JLabel();
        lblEnterStr = new javax.swing.JButton();
        lblEnteredStr = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CS 475 Assignments 1 - 3");
        setPreferredSize(new java.awt.Dimension(350, 325));

        jLabel1.setText("Assignment 2 DPDA");

        jButton1.setText("Open File...");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Close");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        lblStartState.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        lblStartState.setText("Start State");
        lblStartState.setToolTipText("");

        lblAcceptStates.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        lblAcceptStates.setText("Accept States");

        lblAlphabet.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        lblAlphabet.setText("Alphabet");
        lblAlphabet.setAlignmentY(0.0F);
        lblAlphabet.setVerifyInputWhenFocusTarget(false);
        lblAlphabet.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        lblEnterStr.setText("Enter String...");
        lblEnterStr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblEnterStrActionPerformed(evt);
            }
        });

        lblEnteredStr.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        lblEnteredStr.setText("Entered String........");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblStartState, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblAlphabet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAcceptStates)
                            .addComponent(lblEnteredStr))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(lblEnterStr)
                .addContainerGap(126, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblStartState)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblAcceptStates)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblAlphabet)
                .addGap(18, 18, 18)
                .addComponent(lblEnterStr)
                .addGap(18, 18, 18)
                .addComponent(lblEnteredStr)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(127, 127, 127)
                                .addComponent(jButton1)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1)
                .addGap(12, 12, 12)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        System.exit(0);// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int ret = jchooser.showOpenDialog(this);
        if(ret == JFileChooser.APPROVE_OPTION){
            try {
                BufferedReader reader = new BufferedReader(new FileReader(jchooser.getSelectedFile()));
                String line;
                int lineNum = 0;
                while ((line = reader.readLine()) != null) {
                    switch(lineNum){
                        case 0:
                            fa.setStartState(line);
                            //startState = line;
                            lblStartState.setText("Start State:   " + line);
                            break;
                        case 1:
                            String[] arrAcceptStates = line.split(" ");
                            for (String str : arrAcceptStates){
                                fa.setAcceptStates(str);
                            }
                            String accepts = String.join(" ", fa.getAcceptStates());
                            lblAcceptStates.setText("Accept States: " + accepts);
                            break;
                        default:
                            //String[] arrTransition = line.split("[\\(||\\)]");
                            String[] arrTransition = line.split(" ");
                            for (String str : arrTransition) {
                                if (str.length() == 1){
                                    char alphLetter = str.charAt(0);
                                    if (!alphabet.contains(alphLetter)) {
                                        alphabet.add(alphLetter);
                                    }
                                } else {
                                fa.setTransitionList(line);
                                }
                            }         
                    }
                    lineNum++;
                }
                StringBuilder strDisplay = new StringBuilder();
                for (char c : alphabet){
                    strDisplay.append(c);
                }
                lblAlphabet.setText("Alphabet:      " + strDisplay);
                reader.close();
            } catch (Exception e) {
                System.out.println(e);
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void lblEnterStrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblEnterStrActionPerformed
        if(alphabet.isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "You must open a file first.");
        } else {
            String inputString = JOptionPane.showInputDialog("Type string to check.", "");
            while(inputString != null){
                if (inputString.isEmpty()){
                    JOptionPane.showMessageDialog(rootPane, "Must enter a string.");
                } else {
                    for (int i = 0; i < inputString.length(); i++){
                        if(!alphabet.contains(inputString.charAt(i))){
                            JOptionPane.showMessageDialog(rootPane, "Invalid character \"" + inputString.charAt(i) + "\" entered.");
                            break;
                        } else if (alphabet.contains(inputString.charAt(i)) && i == inputString.length()-1){
                            lblEnteredStr.setText("Most recent string entered: " + inputString);
                            boolean ret = fa.run(inputString);
                            if(ret){
                                JPanel txtPanel = new JPanel(new GridLayout(2,5));
                                txtPanel.setBackground(Color.GREEN);
                                txtPanel.add(new JLabel("Your String is valid"));
                                JPanel panel = new JPanel(new BorderLayout());
                                panel.add(txtPanel);
                                JOptionPane.showMessageDialog(null, panel, "Valid", JOptionPane.DEFAULT_OPTION);
                            } else {
                                JPanel txtPanel = new JPanel(new GridLayout(2,5));
                                txtPanel.setBackground(Color.RED);
                                txtPanel.add(new JLabel("Your String is NOT valid"));
                                JPanel panel = new JPanel(new BorderLayout());
                                panel.add(txtPanel);
                                JOptionPane.showMessageDialog(null, panel, "Invalid", JOptionPane.DEFAULT_OPTION);
                            }
                        }
                    }

                }
                inputString = JOptionPane.showInputDialog("Type string to check.", "");
            }
        }
    }//GEN-LAST:event_lblEnterStrActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAcceptStates;
    private javax.swing.JLabel lblAlphabet;
    private javax.swing.JButton lblEnterStr;
    private javax.swing.JLabel lblEnteredStr;
    private javax.swing.JLabel lblStartState;
    // End of variables declaration//GEN-END:variables
}
